name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build
      run: dotnet build --configuration Release
    - name: Pack
      run: dotnet pack src/ReadLine/ReadLine.csproj --output nuget-packages --configuration Release
    - name: Add Source
      run: dotnet nuget add source --username christianhood --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github-ch "https://nuget.pkg.github.com/christianhood/index.json"
    - name: Push
      run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }} --source github-ch
